"""Initial migration with profile_pic column

Revision ID: 560abcadc10c
Revises: 
Create Date: 2024-06-27 09:05:27.438127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560abcadc10c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('inn', sa.String(length=100), nullable=False),
    sa.Column('registered_date', sa.Date(), nullable=False),
    sa.Column('authorized_body', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('daily_access_count', sa.Integer(), nullable=True),
    sa.Column('profile_pic', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('company')
    # ### end Alembic commands ###
