"""Add capital column to company table

Revision ID: 7a94170c232c
Revises: fd276c5fd62b
Create Date: 2024-06-27 10:22:01.104065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a94170c232c'
down_revision = 'fd276c5fd62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=250), nullable=True))

    # ### end Alembic commands ###
