"""Initial migration with profile_pic column

Revision ID: fd276c5fd62b
Revises: 560abcadc10c
Create Date: 2024-06-27 09:26:11.885483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd276c5fd62b'
down_revision = '560abcadc10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capital', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('capital')

    # ### end Alembic commands ###
